### ISSUE TITLE
Exports with class.

### ISSUE THREAD

**Issue by GeTechG** [godotjs/GodotJS#48]
If I understand correctly, the class_ field is intended to specify the class of the object.
```ts
@export_(Variant.Type.TYPE_OBJECT, {class_: Texture2D})
```
 But it doesn't work and the editor still has a dropdown list of all possible classes. 

Also it would be nice if you could specify the type for an array like in gdscript.
```gdscript
@export()
var arr: Array[Texture2D]
```

**Comment by ialex32x** [comment]
I'll look into it right away.  
However, the second method you mentioned is not straightforward to implement in typescript without any parser tool (such as ANTLR-like stuff, which is not intended to be integrated) since all 'static' types are erased at runtime. 'reflect-metadata` may be a potential solution. It'll be tried later.

**Comment by ialex32x** [comment]
It's fixed now.

```ts
import { GDictionary, GArray, Node, Texture2D, Variant } from "godot";
import { export_, EnumType, TypePair } from "godot.annotations";

enum TSItemType {
    A, B, C
}

export default class TSAnnotations extends Node {
     // typed hint_string for dictionary require Godot 4.4
    // long version:
    // @export_(Variant.Type.TYPE_DICTIONARY, { class_: TypePair(EnumType(TSItemType), Texture2D) }) 
    test_a!: GDictionary;

    // short version:
    @export_dictionary(EnumType(TSItemType), Texture2D) 
    test_b!: GDictionary;

    @export_array(Texture2D)
    test_c!: GArray<Texture2D>;
}

```

**Comment by GeTechG** [comment]
Yes, that's what I meant about specifying it through the decorator, thanks for adding that, but specifically specifying the object class still doesn't work.
```ts
@export_(Variant.Type.TYPE_OBJECT, {class_: Texture2D})
```

**Comment by GeTechG** [comment]
> JS `Array` can not be transparently handled by GodotJS in this case. And the type for the decorator is not TYPE_OBJECT.

You misunderstood, my original question was not about array at all, I understood how arrays work and it works, I was asking if I can export a single resource via @export

**Comment by ialex32x** [comment]
OK, it's fixed now. Godot use different rules to construct a hint string for OBJECT and ARRAY/DICTIONARY. The implementation in GodotJS godot.annotation needs to be improved later. But it works now for OBJECT with a given `class_` (Resource/Object type).
